module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^@/\\(auth\\)/(.*)$': '<rootDir>/app/(auth)/$1',
    '^@/\\(tabs\\)/(.*)$': '<rootDir>/app/(tabs)/$1',
    '^@/screens/(.*)$': '<rootDir>/app/screens/$1',
    '^@/index$': '<rootDir>/app/index.tsx',
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.(png|jpg|jpeg|gif|webp|svg|ttf)$': '<rootDir>/test/fileMock.cjs',
  },
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/.expo/'],
  collectCoverageFrom: [
    'app/**/*.{ts,tsx}',
    'src/**/*.{ts,tsx}',
    '!app/**/*.d.ts',
    '!app/assets/**',
    '!app/screens/settings/about.tsx',
    '!app/screens/settings/faq.tsx',
    '!app/screens/settings/reminders.tsx',
    '!app/screens/settings/verfication.tsx',
    '!app/screens/settings/report/index.tsx',
    '!src/**/*.d.ts',
    '!src/constants/translations/**',
    '!src/common/commonUtils.ts',
    '!src/constants/index.ts',
    '!src/constants/types/**',
    '!src/components/index.ts',
    '!src/hooks/index.ts',
    '!src/hooks/useTranslation.tsx',
    '!src/interface/**',
    '!src/services/api.ts',
    '!src/services/auth.ts',
    '!src/services/user.ts',
    '!src/types/**',
  ],
  coverageThreshold: {
    global: {
      branches: 32,
      functions: 60,
      lines: 62,
      statements: 61,
    },
    'app/_layout.tsx': {
      branches: 65,
      functions: 80,
      lines: 85,
      statements: 85,
    },
    'app/index.tsx': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'app/(auth)/_layout.tsx': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'app/(auth)/login.tsx': {
      branches: 75,
      functions: 80,
      lines: 85,
      statements: 85,
    },
    'src/constants/routes.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/services/session.ts': {
      branches: 45,
      functions: 85,
      lines: 65,
      statements: 65,
    },
    'src/store/registration.tsx': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
    'src/utils/navigation.ts': {
      branches: 100,
      functions: 100,
      lines: 100,
      statements: 100,
    },
  },
};
